[tool.poetry]
authors = ["long2ice <long2ice@gmail.com>"]
build = "build.py"
description = "A fast asyncio MySQL driver"
documentation = "https://github.com/long2ice/asyncmy"
homepage = "https://github.com/long2ice/asyncmy"
include = ["CHANGELOG.md", "LICENSE", "README.md", "struct"]
keywords = ["driver", "asyncio", "mysql"]
license = "Apache-2.0"
name = "asyncmy"
packages = [
    { include = "asyncmy" },
]
readme = "README.md"
repository = "https://github.com/long2ice/asyncmy.git"
version = "0.2.1"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
aiomysql = "*"
bandit = "*"
black = { version = "*", allow-prereleases = true }
cryptography = "*"
cython = "*"
flake8 = "*"
isort = "*"
mypy = "*"
mysqlclient = "*"
pymysql = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-mock = "*"
pytest-xdist = "*"
uvloop = { version = "*", markers = "sys_platform != 'win32'" }

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0", "setuptools", "cython"]

[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38', 'py39']
