[tool.poetry]
name = "asyncmy"
version = "0.2.1"
description = "A fast asyncio MySQL driver"
authors = ["long2ice <long2ice@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/long2ice/asyncmy"
repository = "https://github.com/long2ice/asyncmy.git"
documentation = "https://github.com/long2ice/asyncmy"
keywords = ["driver", "asyncio", "mysql"]
packages = [
    { include = "asyncmy" }
]
include = ["CHANGELOG.md", "LICENSE", "README.md"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flake8 = "*"
isort = "*"
black = "*"
pytest = "*"
pytest-xdist = "*"
pytest-asyncio = "*"
bandit = "*"
pytest-mock = "*"
cython = "*"
mysqlclient = "*"
pymysql = "*"
aiomysql = "*"
uvloop = { version = "*", markers = "sys_platform != 'win32'" }
cryptography = "*"
mypy = "*"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "cython"]
build-backend = "poetry.core.masonry.api"
