name: ci
on:
  push:
    branches-ignore:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      database:
        image: ${{ matrix.database }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123456
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        database: [ "mysql", "mariadb" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        run: |
          pip install -U pip poetry
          poetry config virtualenvs.create false
      - name: Run ci
        run: make ci
