name: ci
on:
  push:
    branches-ignore:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.3
      - name: Config poetry
        run: poetry config experimental.new-installer false
      - name: Run ci
        env:
          MYSQL_PASS: root
        run: make ci
